name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ch.jsan.crimson
        path: app/build/outputs/apk/debug/app-debug.apk

  version-check:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Check version against tag
      run: |
        VER=$(awk -F'["]' '/versionName =/ {print $2}' app/build.gradle.kts)
        if [ "$GITHUB_REF_NAME" != "v$VER" ]; then
          echo "Version $VER does not match the GitHub tag $GITHUB_REF_NAME"
          exit 1
        fi

  upload:
    runs-on: ubuntu-latest
    needs: [ build, version-check ]
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: ch.jsan.crimson
    - name: Upload as new release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: ${{ contains(github.ref_name, '-') }}
        files: |
          ch.jsan.crimson/*.apk
